Improve logger
TwilioDevEd/notifications-quickstart-java pull request #1
Opened 2017-03-28 21:27 UTC by well1791

2017-03-30 10:06 UTC, hortega requested changes
Looking good @well1791 . There is a call to Twilio library in `NotifyUtil` likely to throw an exception, could you catch it and log it as per the story?

2017-03-30 10:06 UTC, hortega commented on notification-quickstart.iml
>      </content>
I think we could add this file to `.gitignore`

2017-03-30 13:54 UTC, well1791 commented on notification-quickstart.iml
>      </content>
thanks for the reviewing! I'll update this change on all repos I've worked on.

2017-03-31 21:57 UTC, joliveros commented
LGTM @well1791

2017-03-31 22:04 UTC, merged